# Generated by Django 6.0.3 on 2026-03-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djgent", "0003_message_and_conversation_usage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="knowledgedocument",
            new_name="djgent_know_namespa_a74548_idx",
            old_name="djgent_know_namespace_fcc6de_idx",
        ),
        migrations.RenameIndex(
            model_name="knowledgedocument",
            new_name="djgent_know_title_be8333_idx",
            old_name="djgent_know_title_3529b8_idx",
        ),
        migrations.RenameIndex(
            model_name="memoryfact",
            new_name="djgent_memo_scope_97b5d7_idx",
            old_name="djgent_memo_scope_70b590_idx",
        ),
        migrations.RenameIndex(
            model_name="memoryfact",
            new_name="djgent_memo_agent_n_a00f2d_idx",
            old_name="djgent_memo_agent_n_1e63ec_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="djgent_mess_convers_52e7e8_idx",
            old_name="djgent_mess_convers_6c0c4f_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="djgent_mess_role_3838fa_idx",
            old_name="djgent_mess_role_382203_idx",
        ),
    ]
