# Generated by Django 6.0.3 on 2026-05-15 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_failed_to_resume_failed(apps, schema_editor):
    """Convert existing 'failed' status to 'resume_failed'."""
    HumanInteractionRequest = apps.get_model("djgent", "HumanInteractionRequest")
    HumanInteractionRequest.objects.filter(status="failed").update(
        status="resume_failed"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("djgent", "0006_human_interaction_langgraph_checkpoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="humaninteractionrequest",
            new_name="djgent_huma_status_4bc6e7_idx",
            old_name="djgent_hum_status_7a4e91_idx",
        ),
        migrations.RenameIndex(
            model_name="humaninteractionrequest",
            new_name="djgent_huma_agent_n_de1678_idx",
            old_name="djgent_hum_agent_n_5b95a2_idx",
        ),
        migrations.RenameIndex(
            model_name="humaninteractionrequest",
            new_name="djgent_huma_thread__8df73c_idx",
            old_name="djgent_hum_thread__1370d2_idx",
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="notes_visible_to_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="operation_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="operation_type",
            field=models.CharField(
                choices=[("tool", "Tool"), ("operation", "Operation")],
                default="tool",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="public_reference",
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="resume_payload_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="resume_payload_key_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="review_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="review_instructions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="review_permission",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_hitl_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="reviewer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="source",
            field=models.CharField(
                choices=[("djgent_native", "Djgent Native"), ("langgraph_hitl", "LangGraph HITL")],
                db_index=True,
                default="djgent_native",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            migrate_failed_to_resume_failed,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="humaninteractionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("resuming", "Resuming"),
                    ("resumed", "Resumed"),
                    ("resume_failed", "Resume Failed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="humaninteractionrequest",
            index=models.Index(
                fields=["source", "status", "-created_at"], name="djgent_huma_source_3e9a97_idx"
            ),
        ),
    ]
