# Generated by Django 6.0.3 on 2026-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djgent", "0007_first_class_human_interaction_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="humaninteractionrequest",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approve", "Approve"),
                    ("reject", "Reject"),
                    ("edit", "Edit"),
                    ("cancel", "Cancel"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
